### ISSUE TITLE
Ignore last comma

### ISSUE THREAD

**Issue by Splinter1984** [Civitasv/mini-json-parser#1]
maybe ignore the last comma characters?
```json
{
  "glossary" : {
    "test": true,
    "hello": null,
    "hello2": "miao\nmiao",
  },
}
```
now it's error behavior
```bash
terminate called after throwing an instance of 'std::logic_error'
  what():  Key must be string!
Aborted (core dumped)
```

**Comment by Civitasv** [comment]
According to 
![image](https://user-images.githubusercontent.com/37768049/198862994-2339f19e-32a8-44d0-bb04-e5819022cbd9.png)
from json.org, comma should not exist after the last key-value pair.

**Comment by Civitasv** [comment]
> comma should not exist after the last key-value pair.

After comma, there should always be key-value pair.

**Comment by Splinter1984** [comment]
ok thanks, i didn't see the spec
