### ISSUE TITLE
用cmake生成后不知道为啥test_parser没成功，test_scanner是正常的

### ISSUE THREAD

**Issue by runningNooooooooob** [Civitasv/mini-json-parser#2]
您好
![HYHEBQUS44VSR9U6~9KL4NT](https://user-images.githubusercontent.com/74545004/216595449-1ff036d8-dd8c-48b0-82ee-03400062fae8.png)
错误信息是这样的，头一次用cmake，不知道哪里操作有问题。

**Comment by Civitasv** [comment]
在 test_parser 里打断点，一步步执行，看看哪里出错

**Comment by runningNooooooooob** [comment]
好的，谢谢回复，我再看看




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Civitasv/mini-json-parser"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月4日(星期六) 中午12:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Civitasv/mini-json-parser] 用cmake生成后不知道为啥test_parser没成功，test_scanner是正常的 (Issue #2)





 
在 test_parser 里打断点，一步步执行，看看哪里出错
